name: Publish Storybook to GitHub Pages
on:
  push:
    branches: [master]

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  storybook-build:
    name: Storybook build
    runs-on: ubuntu-latest
    steps:
      - name: Cloning source code
        uses: actions/checkout@v4
      - name: "`pnpm` installation"
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Configuring Node.js 20 (LTS)
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile
      - name: Linting the source code
        run: pnpm lint
        env:
          NODE_ENV: production

      - name: Checking type consistency
        run: pnpm typecheck
      - name: Building the source code
        run: pnpm build:storybook
      - name: Uploading the artifact
        uses: actions/upload-artifact@v4
        with:
          name: byloth-clay_vue-storybook
          path: .storybook/dist

  storybook-deploy:
    name: Artifact deploy
    needs: storybook-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          name: byloth-clay_vue-storybook

      - name: Configuring GitHub Pages
        uses: actions/configure-pages@v4
      - name: Uploading to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - id: deployment
        name: Deploying to GitHub Pages
        uses: actions/deploy-pages@v4

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
